### ISSUE TITLE
[LetsMoveIt] [bug] Buildings on the floor cannot be moved unless the flooring is moved first

### ISSUE THREAD

**Issue by chguw** [Exblosis/StardewValleyMods#5]
In version 0.5.7, if I disable "Move flooring" then the buildings (like mill or Junimo hut) on the flooring cannot be moved. I don't know if that was the intentional design, but it limits the ability to move the building without moving the flooring.

**Comment by Exblosis** [comment]
Thanks, i fixed it.
Fixed in version 0.6.0
